# Generated by Django 2.1.1 on 2019-10-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
