# Generated by Django 2.1.1 on 2019-10-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='brand',
            new_name='name',
        ),
    ]
