# Generated by Django 2.1.1 on 2019-10-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20191019_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='lte_exists',
            field=models.CharField(max_length=10),
        ),
    ]
